### ISSUE TITLE
Feedback on demo

### ISSUE THREAD

**Issue by lukevalenta** [bwesterb/mtc#1]
Overall, the demo is very clear and easy to follow! Nice work.

* Remove `-noout` from the `openssl` commands at https://github.com/bwesterb/mtc/blob/e0c1537bc330139af8593bb21b7c057f46c02970/README.md?plain=1#L64-L65 - for the first command, `noout` doesn't seem to make a difference, but the second command it caused the public key to not be written for me on macOS.
* When going through the demo, I got `INFO No batches were ready to issue` when I hadn't waited at least 5m (or whatever the batch duration) before running `mtc ca issue`. Maybe explicitly show this message and explain why it's there? Perhaps the message could also include the next timestamp that a batch can be issued. If you reduce the example CA's batch-duration to 1m instead of 5m that might also make going through the demo a little smoother.
* In https://github.com/bwesterb/mtc/tree/main?tab=readme-ov-file#issuing-more-batches, we skip from batch 0 to batch 2, but the commands for issuing batch 1 are missing. This meant that the subsequent `mtc inspect` command that references batch 2 failed for me initially.

**Comment by bwesterb** [comment]
Good points. Improved the README. Will make `mtc ca issue` more helpful when the batch is not yet ready to issue.

**Comment by bwesterb** [comment]
```
2024/01/22 21:17:34 INFO No batches were ready to issue. Next batch ready in 50s.
```
