### ISSUE TITLE
Plans to adapt to version 03 of the draft RFC?

### ISSUE THREAD

**Issue by pohlm01** [bwesterb/mtc#3]
I'm currently writing [a verifier](https://github.com/pohlm01/mct-verifier) for the MTC in Rust for my Master's thesis. It's still in a very early state. Yesterday, the 03 version of your MTC draft RFC [was published](https://datatracker.ietf.org/doc/html/draft-davidben-tls-merkle-tree-certs-03), and some of the data structure has changed. So far, I noticed the change from `TrustAnchor` to `TrustAnchorIdentifier` based on draft RFC [draft-beck-tls-trust-anchor-ids-01 ](https://datatracker.ietf.org/doc/html/draft-beck-tls-trust-anchor-ids-01).
Are there already plans to adopt this repository accordingly? Would you prefer if I try to contribute a PR? If so, that would likely take about a week.

**Comment by bwesterb** [comment]
I [started that work](https://github.com/bwesterb/mtc/commit/c5815c3514e4e185cc0905d4e02dc6fcbc8cd915), but got distracted by NIST's release of ML-KEM. Feel free to pick it up.
